version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - IMAGE_TAG=`date '+%Y%m%d%H%M%S'`
      - export TZ="Asia/Tokyo"
  build:
    commands:
      - echo Building the Laravel project
      - echo Building the Docker image...
      - echo URL $IMAGE_REPO_NAME:$IMAGE_TAG
      - docker build -t my-laravel-app .
      - docker tag my-laravel-app:latest $ECR_REPO_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - echo $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.con/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.con/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Writing image imagedefinitions file...
      - echo '[{"name":"my-laravel-app","imageUri":"'$ECR_REPO_URI:latest'"}]' > imagedefinitions.json
      # - ls -l
      # - cat imagedefinitions.json

artifacts:
  files: imagedefinitions.json
